### PR TITLE
No sig check

### PR DESCRIPTION
**Pull request by magcius**

### CODE REVIEW

**Comment by sgnn7** [comment]
@magcius / @cosimoc If I'm not mistaken with this change you can install any app over dbus by setting the signature to [`null` over dbus]*(https://github.com/endlessm/eos-app-manager/blob/fb0c5adcca61557dff5e0c7df7eef85a1c172e7c/src/eam-transaction-dbus.c#L152-L170) even if `no-signature-file` option isn't set which is a pretty large side-load security hole.

**Comment by magcius** [comment]
Why is it a security hole? All the `--no-security-file` does is simply not set `SignatureFile` option over DBus.

**Comment by sgnn7** [comment]
@magcius Manager runs with elevated privileges and installation can do arbitrary changes to the system. With this change, if you have dbus access you can get root trivially without password, user interaction, or any kind of authentication. While I understand the need for easier debugging, this is a malware side-load goldmine that shouldn't ever be in production imo.

**Comment by magcius** [comment]
This isn't for debugging, this is actually to help sales install applications out-of-band from the app store.

My understanding is that installing an application effectively requires the polkit permissions of root anyway -- you cannot install an application unless you effectively can write to `/endless/` anyway. If not, I must have read the code wrong. My first proposal was that you could only skip the signature check if you had write permission to `/endless/`.

**Comment by sgnn7** [comment]
@magcius Manager runs as `app-manager` user/group [which has write access to /endless](https://github.com/endlessm/eos-app-manager/blob/master/debian/postinst) and you talk to it over DBus as any user (afaik) so the sig is there to verify that you're not passing it unsigned content. Combine that with the fact that we can add [ACE scripts to bundles that get executed on install](https://github.com/endlessm/eos-app-manager/blob/fae8a840ebfc5cdbfab06103ed0f4107ef02e33e/src/eam-install.c#L216-L225), you effectively have root if you have DBus access. I'd suggest we either fix this code up, revert it, and/or add another GPG key in the keyring that we can use for ad-hoc signing of apps so that we send the sales people sigs along with the apps they want.

**Comment by magcius** [comment]
I'm going to fix this code up, then.

**Pull request merged**
